// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7QhNbsN66rrgA3CzImhyTPfmdPVzoOcc',
    appId: '1:192267986897:web:5c3180669aab3127fa62f0',
    messagingSenderId: '192267986897',
    projectId: 'cmsc-23-project-2f698',
    authDomain: 'cmsc-23-project-2f698.firebaseapp.com',
    storageBucket: 'cmsc-23-project-2f698.appspot.com',
    measurementId: 'G-EGHWLJ38M1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHo4NwS7ywjHXTURmWooH_9U1-THbBssU',
    appId: '1:192267986897:android:1d6739345eb1bde6fa62f0',
    messagingSenderId: '192267986897',
    projectId: 'cmsc-23-project-2f698',
    storageBucket: 'cmsc-23-project-2f698.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxCo061GUtebtvHhZ-ne5Ycm7K7J5M3pk',
    appId: '1:192267986897:ios:840fc21577b87a60fa62f0',
    messagingSenderId: '192267986897',
    projectId: 'cmsc-23-project-2f698',
    storageBucket: 'cmsc-23-project-2f698.appspot.com',
    iosClientId: '192267986897-36foqf31uj0aj7gasnjue3oa18o5ius0.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxCo061GUtebtvHhZ-ne5Ycm7K7J5M3pk',
    appId: '1:192267986897:ios:840fc21577b87a60fa62f0',
    messagingSenderId: '192267986897',
    projectId: 'cmsc-23-project-2f698',
    storageBucket: 'cmsc-23-project-2f698.appspot.com',
    iosClientId: '192267986897-36foqf31uj0aj7gasnjue3oa18o5ius0.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
